apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoapp
spec:
  selector:
    matchLabels:
      app: djangoapp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
      labels:
        app: djangoapp
    spec:
      containers:
        - name: djangoapp
          image: tegarimansyah/djangoapp:0.0.3
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:test_password@postgres-monitoring-demo.architect.svc.cluster.local:5432/db_name"
          resources:
            request:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: djangoapp-svc
spec:
  selector:
    app: djangoapp
  ports:
    - port: 8000
      targetPort: 8000
